services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: opentasker-postgres
    environment:
      POSTGRES_DB: opentasker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opentasker-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: opentasker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - opentasker-network

  # Backend API
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend.dev
    container_name: opentasker-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/opentasker
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      API_PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - opentasker-network


  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend.dev
    container_name: opentasker-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    depends_on:
      - backend
    networks:
      - opentasker-network


volumes:
  postgres_data:
  redis_data:

networks:
  opentasker-network:
    driver: bridge 